error: found iterator that can be parallelized
  --> $DIR/main.rs:27:5
   |
LL |     (0..100).into_iter().for_each(|x| println!("{:?}", x));
   |     ^^^^^^^^^^^^^^^^^^^^ help: try using a parallel iterator: `(0..100).into_par_iter()`
   |
   = note: `-D par-iter` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(par_iter)]`

error: found iterator that can be parallelized
  --> $DIR/main.rs:51:5
   |
LL | /     (0..100)
LL | |         .into_iter()
   | |____________________^
   |
help: try using a parallel iterator
   |
LL ~     (0..100)
LL +         .into_par_iter()
   |

error: found iterator that can be parallelized
  --> $DIR/main.rs:86:5
   |
LL |     list.into_iter().for_each(|x| println!("{:?}", x));
   |     ^^^^^^^^^^^^^^^^ help: try using a parallel iterator: `list.into_par_iter()`

error: found iterator that can be parallelized
  --> $DIR/main.rs:102:5
   |
LL |     (0..10).into_iter().for_each(|x| {
   |     ^^^^^^^^^^^^^^^^^^^ help: try using a parallel iterator: `(0..10).into_par_iter()`

error: found iterator that can be parallelized
  --> $DIR/main.rs:185:5
   |
LL |     data.iter()
   |     ^^^^^^^^^^^ help: try using a parallel iterator: `data.par_iter()`

error: found iterator that can be parallelized
  --> $DIR/main.rs:212:5
   |
LL |     numbers.iter().enumerate().for_each(|t| {
   |     ^^^^^^^^^^^^^^ help: try using a parallel iterator: `numbers.par_iter()`

error: found iterator that can be parallelized
  --> $DIR/main.rs:253:30
   |
LL |     let names: Vec<String> = people.iter().map(|p| p.name.clone()).collect();
   |                              ^^^^^^^^^^^^^ help: try using a parallel iterator: `people.par_iter()`

error: found iterator that can be parallelized
  --> $DIR/main.rs:261:37
   |
LL |       let doubled_numbers: Vec<i32> = numbers
   |  _____________________________________^
LL | |         .into_iter()
   | |____________________^
   |
help: try using a parallel iterator
   |
LL ~     let doubled_numbers: Vec<i32> = numbers
LL +         .into_par_iter()
   |

error: aborting due to 8 previous errors

